<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) LOCKON CO.,LTD. All Rights Reserved.
 *
 * http://www.lockon.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\SSProductListPage\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\SSProductListPage\Entity\CategoryLayout;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * CategoryLayoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryLayoutRepository extends AbstractRepository
{
    /**
     * CategoryLayoutRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, CategoryLayout::class);
    }
}
