<?php

namespace Plugin\SSProductListPage\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductListBlockPositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductListBlockPositionRepository extends EntityRepository
{
}
